// sdk/qrcode/SelfQRcode.tsx
import React, { useEffect, useState, useRef } from 'react';
import { BounceLoader } from 'react-spinners';
import Lottie from 'lottie-react';
import CHECK_ANIMATION from './animations/check_animation.json';
import X_ANIMATION from './animations/x_animation.json';
import LED from './components/LED';
import { REDIRECT_URL, WS_DB_RELAYER } from '../../common/src/constants/constants';
import { v4 as uuidv4 } from 'uuid';
import { QRcodeSteps } from './utils/utils';
import { containerStyle, ledContainerStyle, qrContainerStyle } from './utils/styles';
import { QRCodeSVG } from 'qrcode.react';
import { initWebSocket } from './utils/websocket';
import { getUniversalLink, SelfApp, SelfAppBuilder } from '../../common/src/utils/appType';

interface SelfQRcodeProps {
  selfApp: SelfApp;
  onSuccess: () => void;
  onError: (data: {error_code?: string, reason?: string}) => void;
  type?: 'websocket' | 'deeplink';
  websocketUrl?: string;
  size?: number;
  darkMode?: boolean;
  children?: React.ReactNode;
}

const SelfQRcodeWrapper = (props: SelfQRcodeProps) => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);

  if (!isClient) {
    return null;
  }
  return <SelfQRcode {...props} />;
};

const SelfQRcode = ({
  selfApp,
  onSuccess,
  onError,
  type = 'websocket',
  websocketUrl = WS_DB_RELAYER,
  size = 300,
  darkMode = false,
}: SelfQRcodeProps) => {
  const [proofStep, setProofStep] = useState(QRcodeSteps.WAITING_FOR_MOBILE);
  const [proofVerified, setProofVerified] = useState(false);
  const [sessionId, setSessionId] = useState('');
  const socketRef = useRef<ReturnType<typeof initWebSocket> | null>(null);

  useEffect(() => {
    setSessionId(uuidv4());
  }, []);

  useEffect(() => {
    if (sessionId && !socketRef.current) {
      console.log('[QRCode] Initializing new WebSocket connection');
      socketRef.current = initWebSocket(
        websocketUrl,
        {
          ...selfApp,
          sessionId: sessionId
        },
        type,
        setProofStep,
        onSuccess,
        onError,
      );
    }

    return () => {
      console.log('[QRCode] Cleaning up WebSocket connection');
      if (socketRef.current) {
        socketRef.current();
        socketRef.current = null;
      }
    };
  }, [sessionId, type, websocketUrl, onSuccess, selfApp]);

  if (!sessionId) {
    return null;
  }

  const renderProofStatus = () => (
    <div style={containerStyle}>
      <div style={ledContainerStyle}>
        <LED connectionStatus={proofStep} />
      </div>
      <div style={qrContainerStyle(size)}>
        {(() => {
          switch (proofStep) {
            case QRcodeSteps.PROOF_GENERATION_STARTED:
            case QRcodeSteps.PROOF_GENERATED:
              return <BounceLoader loading={true} size={200} color="#94FBAB" />;
            case QRcodeSteps.PROOF_GENERATION_FAILED:
              return (
                <Lottie
                  animationData={X_ANIMATION}
                  style={{ width: 200, height: 200 }}
                  onComplete={() => {
                    setProofStep(QRcodeSteps.WAITING_FOR_MOBILE);
                  }}
                  loop={false}
                />
              );
            case QRcodeSteps.PROOF_VERIFIED:
              return (
                <Lottie
                  animationData={CHECK_ANIMATION}
                  style={{ width: 200, height: 200 }}
                  onComplete={() => {
                    setProofStep(QRcodeSteps.WAITING_FOR_MOBILE);
                  }}
                  loop={false}
                />
              );
            default:
              return (
                <QRCodeSVG
                  value={type === 'websocket' ? `${REDIRECT_URL}?sessionId=${sessionId}` : getUniversalLink({
                    ...selfApp,
                    sessionId: sessionId
                  })}
                  size={size}
                  bgColor={darkMode ? '#000000' : '#ffffff'}
                  fgColor={darkMode ? '#ffffff' : '#000000'}
                />
              );
          }
        })()}
      </div>
    </div>
  );

  return <div style={containerStyle}>{renderProofStatus()}</div>;
};
// Export the wrapper component as the default export
export default SelfQRcodeWrapper;

// Also export other components/types that might be needed
export { SelfQRcode, SelfApp, SelfAppBuilder };

// sdk/qrcode-angular/src/lib/components/self-qrcode/self-qrcode.component.ts
import { ChangeDetectionStrategy, Component, Input, OnDestroy, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { v4 as uuidv4 } from 'uuid';

import type { SelfApp } from '../../common';
import { getUniversalLink, REDIRECT_URL, WS_DB_RELAYER } from '../../common';
import { QRcodeSteps } from '../../utils/utils';
import { WebSocketService } from '../../services/websocket.service';
import { LedComponent } from '../led/led.component';
import { AnimationOptions, LottieComponent, provideLottieOptions } from 'ngx-lottie';

import { QRCodeComponent } from 'angularx-qrcode';
import CHECK_ANIMATION from '../animations/check_animation.json';
import X_ANIMATION from '../animations/x_animation.json';


export interface SelfQRcodeProps {
  selfApp: SelfApp;
  onSuccess: () => void;
  onError: (data: { error_code?: string; reason?: string }) => void;
  type?: 'websocket' | 'deeplink';
  websocketUrl?: string;
  size?: number;
  darkMode?: boolean;
}

@Component({
  selector: 'lib-self-qrcode',
  standalone: true,
  imports: [CommonModule, LedComponent, QRCodeComponent, LottieComponent],
  providers: [
    provideLottieOptions({ player: () => import('lottie-web') })
  ],
  templateUrl: './self-qrcode.component.html',
  styleUrls: ['./self-qrcode.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SelfQRcodeComponent implements OnInit, OnDestroy {
  @Input() selfApp!: SelfApp;
  @Input() successFn!: () => void;
  @Input() errorFn!: (data: { error_code?: string; reason?: string }) => void;
  @Input() type: 'websocket' | 'deeplink' = 'websocket';
  @Input() websocketUrl: string = WS_DB_RELAYER;
  @Input() size: number = 300;
  @Input() darkMode: boolean = false;

  // Signals for reactive state management
  proofStep = signal<number>(QRcodeSteps.WAITING_FOR_MOBILE);
  sessionId = signal<string>('');
  qrCodeValue = signal<string>('');

  // Expose QRcodeSteps for template access
  QRcodeSteps = QRcodeSteps;

  // Lottie animation instances
  successOptions: AnimationOptions = {
    animationData: CHECK_ANIMATION,
    loop: false,
    autoplay: true,
  };

  errorOptions: AnimationOptions = {
    animationData: X_ANIMATION,
    loop: false,
    autoplay: true,
  };

  constructor(private webSocketService: WebSocketService) {}

  ngOnInit(): void {
    // Generate session ID
    const newSessionId = uuidv4();
    this.sessionId.set(newSessionId);
    console.log('[SelfQRcode] sessionId', newSessionId);

    // Initialize WebSocket connection
    this.initializeWebSocket();

    // Set up QR code value
    this.updateQRCodeValue();
  }

  ngOnDestroy(): void {
    // Cleanup is handled by the WebSocketService
    this.webSocketService.cleanup();
  }

  private initializeWebSocket(): void {
    const sessionId = this.sessionId();
    console.log('[SelfQRcode] sessionId', sessionId);
    if (!sessionId) return;

    // Create selfApp with session ID
    const selfAppWithSession = {
      ...this.selfApp,
      sessionId: sessionId
    };

    // Initialize WebSocket connection
    this.webSocketService.initializeConnection(
      this.websocketUrl,
      selfAppWithSession,
      this.type,
      this.successFn,
      this.errorFn
    );

    // Subscribe to proof step updates
    this.webSocketService.proofStep$.subscribe((step: number) => {
      this.proofStep.set(step);
    });
  }

  private updateQRCodeValue(): void {
    const sessionId = this.sessionId();
    if (!sessionId) return;

    let qrValue: string;

    if (this.type === 'websocket') {
      qrValue = `${REDIRECT_URL}?sessionId=${sessionId}`;
    } else {
      qrValue = getUniversalLink({
        ...this.selfApp,
        sessionId: sessionId
      });
    }

    this.qrCodeValue.set(qrValue);
  }

  resetToWaiting(): void {
    this.webSocketService.resetStep();
  }
}

<div class="container">
  <div class="led-container">
    <lib-led [connectionStatus]="proofStep()" [size]="8"></lib-led>
  </div>

  <div class="qr-container" [style.width.px]="size" [style.height.px]="size">
    <!-- Error -->
    <ng-lottie
      *ngIf="proofStep() === QRcodeSteps.PROOF_GENERATION_FAILED"
      [options]="errorOptions"
      style="width:200px; height:200px"
      (complete)="resetToWaiting()">
    </ng-lottie>

    <!-- Success -->
    <ng-lottie
      *ngIf="proofStep() === QRcodeSteps.PROOF_VERIFIED"
      [options]="successOptions"
      style="width:200px; height:200px"
      (complete)="resetToWaiting()">
    </ng-lottie>

    <!-- Default QR -->
    <div
      [hidden]="(proofStep() === QRcodeSteps.PROOF_GENERATION_STARTED)
            || (proofStep() === QRcodeSteps.PROOF_GENERATED)
            || (proofStep() === QRcodeSteps.PROOF_GENERATION_FAILED)
            || (proofStep() === QRcodeSteps.PROOF_VERIFIED)">
      <qrcode
        [qrdata]="qrCodeValue()"
        [width]="size"
        [errorCorrectionLevel]="'M'"
        [colorDark]="darkMode ? '#ffffff' : '#000000'"
        [colorLight]="darkMode ? '#000000' : '#ffffff'">
      </qrcode>
    </div>
  </div>
</div>
